---
title: "Case Study_2"
authors: "Kumar Ramasanduran, Julius Mwangi"
date: "July 29, 2018"
output: html_document
---



## INTRODUCTION
*what is the project about - talk about the pumps

A pump is a device thatpushes liquids, gasses and some light solids through a mechanical process from one loaction to another. 
They simplify the shifting processes and improve on equipment operational efficiencies. They are used in myriad places including human bodies, engines, water and oil wells etc. 

Over the years, pumps have become more and more efficeint in their operation but equaly expensive to purchase and maintain.  To enhance their efficiency, pumps are installed as near to the source of what they are hauling as poosible. Often, as in the cse of an oil well, this wold be thousands of fee below the earth, or in the case of  ahuman body this will be close to the heart as possible.

*What is the impact of failing pumps

When a pump fails, it may stall an entire process.  In the case of a human being, a heart pump failure may result in death if immediate resoultion is not found. In other instances e.g. oil well, this could mean heavy machinery and field workers being idle as they wait for the replacement. In addition, pump replacement requires specialized techncians and could take severall hours to uninstall the bad pump and install the new pump. One pum faiure could also affect several a=other processes, costing the company thousands of dollars if it happenes witout proper preparations.For example, it may require making immediate arrangements to divertoil delivert to other oil reservoirs, which might not be in a caocity to hndle extra capacity.

*What causes pump failure

An article posted on the Plant Wellness Way EAM website, "List of 600+ Centrifugal Pump Set Failure Modes" indicated there are over 600 failure modes. In other words, unless you see the actual failed unit it may be difficult to know whay the unit failed.This is worrisomne to any plant manager interetsed to meet deadlines and avoid pump failures. The aricle further distributes pump failure between human error e.g. instalation error, wrong pump being installed, etc or by Materials-of-Construction failure. ^
[https://www.lifetime-reliability.com/cms/free-articles/reliability-improvement/pump-failure-modes-list/]

## PROBLEM STATEMENT
Oil pumps are critical to the efficiency of oil wells. When an oil well is dug, a pump is required to pump the oil out of the well into a storage or to a delivery pipe that delivers the oil into a reservoir near the refinery, where another pump will be used to um the oil into the refinery. When the oils is refined, it will require another pump to pump the oil into other reservoirs waiting distribution. When a (one) pump therefore fails, it’s not only costly to remove and replace it, but there is also a cascade effect as it involves not only halting oil production, but transportation as well, jamming reservoirs, and utilizing specialized personnel and equipment to pull the pump out of the well and replace it with a new one according to an article "Pump Failure Prediction" ^[https://www.maana.io/digital-transformation/pump-failure-prediction/]

If we successfuly predict pump failure before it happens, we can provide this information to the maintenance team who will in turn schedule a close down, and replace all the pumps predicted as calpable to failure. This scheduled maintenance will reduce the indiual replacement cost as specialized pesonnel will pull and replace several pumps; In addition, the prior arrangement will have been made to manage other dependant reservoirs, and also send staff on vacation as the maintenance is being performed. 

## DATA SETS
Our client provided us with eight data sets which we considered to be relatively clean. We shall:
1) Read data from eight different files 
2) Split the data into training and validation sets
3) Build a model using RandomForest. 

## APPROACH
on running the model using RandomForest, it generated a class error of ) for the traiing set. When we tested the model against validation set, the preditcion accuaray was 100%, even after removing some features. 


```{r}
BearingWear <- read.csv("C:\\Users\\KRamasundaram\\Documents\\MSDS 6306\\Case Study 2\\Data Set\\Bearing_Wear.csv")
head(BearingWear)
Cavitation <- read.csv("C:\\Users\\KRamasundaram\\Documents\\MSDS 6306\\Case Study 2\\Data Set\\Cavitation.csv")
ClosedPressure <- read.csv("C:\\Users\\KRamasundaram\\Documents\\MSDS 6306\\Case Study 2\\Data Set\\Closed_pressure_side.csv")
ClosedSuction <- read.csv("C:\\Users\\KRamasundaram\\Documents\\MSDS 6306\\Case Study 2\\Data Set\\Closed_Suction_Side.csv")
CouplingWear <- read.csv("C:\\Users\\KRamasundaram\\Documents\\MSDS 6306\\Case Study 2\\Data Set\\Coupling_Wear.csv")
Imbalance <- read.csv("C:\\Users\\KRamasundaram\\Documents\\MSDS 6306\\Case Study 2\\Data Set\\Imbalance.csv")
Misalignment <- read.csv("C:\\Users\\KRamasundaram\\Documents\\MSDS 6306\\Case Study 2\\Data Set\\Misalignment.csv")
Normal_Ops <- read.csv("C:\\Users\\KRamasundaram\\Documents\\MSDS 6306\\Case Study 2\\Data Set\\Normal_Operation.csv")

BearingWear$Outcome <- c("Bearing Wear")
Cavitation$Outcome <- c("Cavitation")
ClosedPressure$Outcome <- c("ClosedPressure")
ClosedSuction$Outcome <- c("ClosedSuction")
CouplingWear$Outcome <- c("CouplingWear")
Imbalance$Outcome <- c("Imbalance")
Misalignment$Outcome <- c("Misalignment")
Normal_Ops <- c("Normal")

clean_data <- merge(BearingWear, Cavitation)
head(clean_data)
head(Cavitation)
clean_data <- rbind(BearingWear, ClosedPressure)
```

